name: CI

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        example:
          - commands_and_menus
          - datagrid 
          - hello_world
          - jupyter_widgets
          - kernel_messaging
          - kernel_output
          # - serving_files
          - signals_and_buttons
          - widgets

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the dependencies
      run: python -m pip install jupyterlab
    - name: Install the extension
      run: |
        cd ${EXAMPLE_NAME}
        jlpm && jlpm run build
        jupyter labextension link .
        python -m jupyterlab.browser_check
      env:
        EXAMPLE_NAME: ${{ matrix.example }}
